services:
  docs-mcp-server:
    image: ghcr.io/arabold/docs-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["--protocol", "http", "--port", "6280"]
    # platform: linux/amd64
    container_name: docs-mcp-server
    ports:
      - "6280:6280"
    env_file:
      - .env
    environment:
      - MCP_PORT=6280
    volumes:
      - docs-mcp-data:/data
      - /Users/bst/Developer/MCP/docs-mcp-server/docs:/docs:ro

  docs-mcp-web:
    image: ghcr.io/arabold/docs-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["web", "--port", "6281"]
    # platform: linux/amd64
    container_name: docs-mcp-web
    ports:
      - "6281:6281"
    env_file:
      - .env
    environment:
      - WEB_PORT=6281
    volumes:
      - docs-mcp-data:/data
      - /Users/bst/Developer/MCP/docs-mcp-server/docs:/docs:ro

volumes:
  docs-mcp-data:
    name: docs-mcp-data
